#!/usr/bin/env python3
"""Convert a Cloudflare D1 (SQLite) export into Postgres-loadable SQL.

The D1 store and the Supabase Postgres schema were generated from the same
design, so this is a data move, not a schema translation: the Postgres side is
built from supabase/migrations first, and this only carries rows across.

Why introspection rather than a hand-written column map: a hard-coded map is a
second copy of the schema that drifts silently, and the failure mode is a column
quietly not migrated. The Postgres column list is read from the live target, so a
mismatch is reported instead of guessed.

Type handling is deliberately thin. D1 stores uuids, ISO-8601 timestamps and
JSON all as TEXT, and booleans as INTEGER 0/1 with a CHECK. Postgres coerces the
string literals '…', '2026-08-29T14:08:59.237Z', '{"a":1}' and '0'/'1' to uuid,
timestamptz, jsonb and boolean respectively, so emitting every value as a quoted
literal is correct and avoids a per-type ladder that could get a cast wrong.

Usage:
  d1-to-postgres.py --sqlite d1.sqlite --columns pg-columns.tsv --out data.sql

`pg-columns.tsv` is `table<TAB>column` lines from the target, i.e.
  select table_name, column_name from information_schema.columns
   where table_schema='public' order by table_name, ordinal_position;
"""

import argparse
import sqlite3
import sys

# D1 bookkeeping and SQLite internals: never part of the application data.
SKIP_TABLES = {"d1_migrations", "hyn_migration_state", "sqlite_sequence"}

# Load order matters even with triggers and FK checks disabled, because a
# self-referencing or parent/child pair still reads better restored in order and
# a partial failure leaves a comprehensible state. Parents first.
PRIORITY = [
    "profiles",
    "admin_allowlist",
    "nodes",
    "notification_templates",
    "email_preferences",
    "delivery_rules",
    "delivery_digest_settings",
]


def lit(v, pgtype=None):
    """Render one SQLite value as a Postgres literal for a column of pgtype."""
    if v is None:
        return "NULL"
    if pgtype == "boolean":
        # D1 stores booleans as INTEGER 0/1 under a CHECK. Postgres will not
        # coerce a bare 0 to boolean in an INSERT (only a quoted '0' would), so
        # this is resolved here rather than relying on implicit casting.
        if isinstance(v, (int, float)):
            return "false" if int(v) == 0 else "true"
        s = str(v).strip().lower()
        return "true" if s in ("1", "t", "true", "yes") else "false"
    if isinstance(v, (int, float)):
        return repr(v) if isinstance(v, float) else str(v)
    if isinstance(v, bytes):
        return "'\\x" + v.hex() + "'::bytea"
    # Single quotes doubled; E'' not used so backslashes stay literal, which is
    # what standard_conforming_strings=on (the default) already gives us.
    return "'" + str(v).replace("'", "''") + "'"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sqlite", required=True)
    ap.add_argument("--columns", required=True, help="table<TAB>column lines from the target")
    ap.add_argument("--out", required=True)
    ap.add_argument("--report", default="-")
    args = ap.parse_args()

    pg = {}
    pgtype = {}
    with open(args.columns) as fh:
        for line in fh:
            line = line.rstrip("\n")
            if not line or "\t" not in line:
                continue
            parts = line.split("\t")
            t, c = parts[0].strip(), parts[1].strip()
            pg.setdefault(t, []).append(c)
            if len(parts) > 2:
                pgtype[(t, c)] = parts[2].strip().lower()

    db = sqlite3.connect(args.sqlite)
    db.text_factory = str
    have = [r[0] for r in db.execute(
        "select name from sqlite_master where type='table' order by name")]

    tables = [t for t in have if t not in SKIP_TABLES]
    ordered = [t for t in PRIORITY if t in tables] + \
              sorted(t for t in tables if t not in PRIORITY)

    out = open(args.out, "w")
    rep = sys.stdout if args.report == "-" else open(args.report, "w")

    out.write("-- Generated by scripts/d1-to-postgres.py — D1 data for Postgres.\n")
    out.write("-- Apply supabase/migrations (or schema.sql) FIRST; this is data only.\n")
    out.write("begin;\n")
    # Disables triggers AND foreign-key validation for this session, so rows can
    # be loaded parent-last without inventing a full topological sort, and no
    # trigger fabricates a duplicate profile while we are restoring one.
    out.write("set session_replication_role = replica;\n\n")

    total = 0
    skipped_tables, col_notes = [], []

    for t in ordered:
        if t not in pg:
            skipped_tables.append((t, "no such table in Postgres target"))
            continue
        scols = [r[1] for r in db.execute('pragma table_info("%s")' % t)]
        shared = [c for c in scols if c in pg[t]]
        missing_in_pg = [c for c in scols if c not in pg[t]]
        missing_in_d1 = [c for c in pg[t] if c not in scols]
        if not shared:
            skipped_tables.append((t, "no overlapping columns"))
            continue
        if missing_in_pg or missing_in_d1:
            col_notes.append((t, missing_in_pg, missing_in_d1))

        collist = ", ".join('"%s"' % c for c in shared)
        sel = ", ".join('"%s"' % c for c in shared)
        n = 0
        out.write("-- %s\n" % t)
        for row in db.execute('select %s from "%s"' % (sel, t)):
            vals = ", ".join(lit(v, pgtype.get((t, c))) for c, v in zip(shared, row))
            out.write('insert into public."%s" (%s) values (%s) on conflict do nothing;\n'
                      % (t, collist, vals))
            n += 1
        out.write("\n")
        total += n
        print("  %-26s %6d rows  (%d cols)" % (t, n, len(shared)), file=rep)

    out.write("set session_replication_role = origin;\n")
    out.write("commit;\n")
    out.close()

    print("\ntotal rows emitted: %d" % total, file=rep)
    if col_notes:
        print("\ncolumn differences (carried where shared):", file=rep)
        for t, a, b in col_notes:
            if a:
                print("  %s: in D1 only -> %s" % (t, ", ".join(a)), file=rep)
            if b:
                print("  %s: in PG only -> %s" % (t, ", ".join(b)), file=rep)
    if skipped_tables:
        print("\nskipped tables:", file=rep)
        for t, why in skipped_tables:
            print("  %s: %s" % (t, why), file=rep)


if __name__ == "__main__":
    main()
